### ISSUE TITLE
UNRESOLVED DEPENDENCIES  org.grails.plugins#yammer-metrics;0.2-SNAPSHOT: not found for 0.6.4

### ISSUE THREAD

**Issue by aberbenni** [jorgeuriarte/grails-i18n-fields-plugin#8]
The 0.6.4 version does not work, yammer-metrics dependency is not resolved.

**Comment by fniwes** [comment]
0.6.4 is not being actively develop. Please use branch redis_integration.
It is not final yet.. but will be in a few days.

Or use a older version of 0.6.4 branch which will work as espected.

**Comment by aberbenni** [comment]
I'm using redis_integration branch but I would like to disable redis, here is my config:

```
i18nFields {
    // Which locales do we know
    locales = ["en", "it_IT"]

    // Of the known locales, which locales should be stored in redis
    redisLocales = []

    // If can not fetch a locale from redis, which non-redis locale should we use
    defaultLocale = "en"   
} 
```

And this is the exception I receive:

```
[http-bio-8080-exec-1] ERROR errors.GrailsExceptionResolver  - ConnectException occurred when processing request: [GET] /myapp/mycontroller/create
Connection refused. Stacktrace follows:

redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused
    at redis.clients.jedis.Connection.connect(Connection.java:134)
    at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:69)
    at redis.clients.jedis.Connection.sendCommand(Connection.java:79)
    at redis.clients.jedis.BinaryClient.hmset(BinaryClient.java:227)
    at redis.clients.jedis.Client.hmset(Client.java:153)
    at redis.clients.jedis.Jedis.hmset(Jedis.java:715)
    at redis.clients.jedis.JedisCommands$hmset.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at i18nfields.I18nFieldsHelper.push(I18nFieldsHelper.groovy:296)
    at i18nfields.I18nFieldsHelper$push.callStatic(Unknown Source)
        ...
```

**Comment by fniwes** [comment]
I didn't test it but should work. The downside is that the jedis library is
still needed

I will try to make a minute or two today, to do a plugin version without
redis. Should be fairly easy.

**Comment by aberbenni** [comment]
Thanks, in this way we will have a plugin that should work in both modes (DB or REDIS or MIXED?) by development needs.
At the moment I only need "BD mode", but I'm evaluating redis for future relase of my app.

**Comment by baqlawi** [comment]
Hi
I'm new to both Grails & GitHub. I have an I18n-based project, where I added I18n-fields v0.8.1 as a dependency plugin for my project. since then, I'm getting an issue of duplicate fields/properties (only for the i18n-fields applied).
I googled for this issue and was able to find this thread. Hope you will be able to help me with this issue.

I'm using GGTS 3.5.0, with GRAILS 2.3.7.

How can I use branch redis_integration, if it really solve this issue? How can I configure it for my application? (I'm new to GitHub & Grails. any reference would be appreciated a lot)
[It is not final yet.. but will be in a few days.] hope it's final now.
